spring:
  datasource:
    # url: jdbc:postgresql://localhost:5432/medical_visits
    url: jdbc:postgresql://medicalvisitsdb.postgres.database.azure.com:5432/medicalvisitsdb
    username: postgres
    password: Admin12345
    # driver-class-name: org.postgresql.Driver
  jpa:
#    properties:
#      hibernate:
#        jdbc:
#          lob:
#            non_contextual_creation: 'true'
    hibernate:
      # Hibernate ddl auto (create, create-drop, validate, update)
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  data:
    jdbc:
      repositories:
        enabled: 'false'

server:
  address: https://medicalvisits.azurewebsites.net
  # port: 8081
