spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/medical_visits
    password: admin
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: 'true'
    hibernate:
      # Hibernate ddl auto (create, create-drop, validate, update)
      ddl-auto: update
  data:
    jdbc:
      repositories:
        enabled: 'false'

server:
  port: 8081